import { Faction } from "./factions";

export const CREWMATE_ROLES = [
  "Crewmate",
  "Engineer",
  "Scientist",
  "Tracker",
  "Noisemaker",
  "Detective",
  "Bait",
  "Lighter",
  "Mayor",
  "SabotageMaster",
  "Sheriff",
  "Snitch",
  "SpeedBooster",
  "Trapper",
  "Dictator",
  "Doctor",
  "Seer",
  "TimeManager",
  "Gasp",
  "VentMaster",
  "ToiletFan",
  "Bakery",
  "FortuneTeller",
  "TaskStar",
  "PonkotuTeller",
  "UltraStar",
  "MeetingSheriff",
  "GuardMaster",
  "Shyboy",
  "Balancer",
  "ShrineMaiden",
  "Comebacker",
  "WhiteHacker",
  "WolfBoy",
  "NiceAddoer",
  "InSender",
  "Staff",
  "Efficient",
  "Psychic",
  "SwitchSheriff",
  "NiceLogger",
  "Android",
  "King",
  "AmateurTeller",
  "Cakeshop",
  "Snowman",
  "Stolener",
  "VentOpener",
  "VentHunter",
  "Walker",
  "CandleLighter",
  "Express",
  "Inspector",
  "AllArounder",
  "Observer",
  "Satellite",
  "Merlin",
];

export const IMPOSTOR_ROLES = [
  "Impostor",
  "Shapeshifter",
  "Phantom",
  "Viper",
  "BountyHunter",
  "FireWorks",
  "Mafia",
  "SerialKiller",
  "ShapeMaster",
  "Sniper",
  "Vampire",
  "Witch",
  "Warlock",
  "Mare",
  "Penguin",
  "Puppeteer",
  "TimeThief",
  "EvilTracker",
  "Stealth",
  "NekoKabocha",
  "EvilHacker",
  "Insider",
  "Bomber",
  "TeleportKiller",
  "AntiReporter",
  "Tairou",
  "Evilgambler",
  "Notifier",
  "Magician",
  "Decrescendo",
  "Curser",
  "Alien",
  "AlienHijack",
  "SpeedStar",
  "EvilTeller",
  "Limiter",
  "ProgressKiller",
  "Mole",
  "EvilAddoer",
  "Reloader",
  "Jumper",
  "EarnestWolf",
  "Amnesiac",
  "Camouflager",
  "ConnectSaver",
  "EvilSatellite",
  "ProBowler",
  "EvilMaker",
  "Eraser",
  "QuickKiller",
  "CharismaStar",
  "Ballooner",
  "BorderKiller",
  "ShapeKiller",
  "Assassin",
];

export const MADMATE_ROLES = [
  "MadGuardian",
  "Madmate",
  "MadSnitch",
  "MadAvenger",
  "SKMadmate",
  "MadJester",
  "MadTeller",
  "MadBait",
  "MadReduced",
  "MadWorker",
  "MadTracker",
  "MadChanger",
  "MadSuicide",
  "MadBetrayer",
  "Nue",
];

export const NEUTRAL_ROLES = [
  "Arsonist",
  "Egoist",
  "Jester",
  "Opportunist",
  "PlagueDoctor",
  "SchrodingerCat",
  "Terrorist",
  "Executioner",
  "Jackal",
  "Remotekiller",
  "Chef",
  "JackalMafia",
  "CountKiller",
  "GrimReaper",
  "Madonna",
  "Jackaldoll",
  "Workaholic",
  "Monochromer",
  "DoppelGanger",
  "MassMedia",
  "Chameleon",
  "Banker",
  "BakeCat",
  "Emptiness",
  "JackalAlien",
  "CurseMaker",
  "PhantomThief",
  "Fox",
  "Turncoat",
  "Vulture",
  "SantaClaus",
  "Missioneer",
  "Strawdoll",
  "Fool",
  "TaskPlayerB",
];

export const HIDE_AND_SEEK_ROLES = ["HASFox", "HASTroll"];

export const OTHER_ROLES = ["GM", "Driver", "Braid", "Vega", "Altair"];

export const ROLE_SETS: Record<Faction, Set<string>> = {
  Crewmate: new Set(CREWMATE_ROLES),
  Impostor: new Set(IMPOSTOR_ROLES),
  Madmate: new Set(MADMATE_ROLES),
  Neutral: new Set([...NEUTRAL_ROLES, ...HIDE_AND_SEEK_ROLES]),
  Other: new Set(OTHER_ROLES),
};

export const ROLE_FAMILIES = {
  CREWMATE_ROLES,
  IMPOSTOR_ROLES,
  MADMATE_ROLES,
  NEUTRAL_ROLES,
  HIDE_AND_SEEK_ROLES,
  OTHER_ROLES,
};
